exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [pre-commit]
fail_fast: true

# To update pre-commit hooks, run `pre-commit autoupdate` in the terminal.
# Then update the versions in `conda-env/dev.yml`.
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.13.2
      hooks:
          # Sort the imports
          - id: ruff
            name: ruff-sort-imports
            args: [--select, I, --fix]
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.18.2
      hooks:
          - id: mypy
            args: ["--config=backend/pyproject.toml"]
