"""Make case_name in simulations table non-nullable

Revision ID: 2479a4b72048
Revises: a81333263984
Create Date: 2025-09-30 12:20:16.083766

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2479a4b72048"
down_revision: Union[str, Sequence[str], None] = "a81333263984"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulations", "case_name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulations", "case_name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    # ### end Alembic commands ###
