"""Rename comp_set_alias to compset_alias

Revision ID: cd588c054df9
Revises: 46e20d34f20d
Create Date: 2025-09-29 12:48:41.133453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd588c054df9"
down_revision: Union[str, Sequence[str], None] = "46e20d34f20d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulations",
        "comp_set_alias",
        new_column_name="compset_alias",
        existing_type=sa.String(length=120),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulations",
        "compset_alias",
        new_column_name="comp_set_alias",
        existing_type=sa.String(length=120),
        nullable=False,
    )
    # ### end Alembic commands ###
