"""Make simulation name and case name required and unique

Revision ID: a81333263984
Revises: cd588c054df9
Create Date: 2025-09-30 11:23:12.909512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81333263984'
down_revision: Union[str, Sequence[str], None] = 'cd588c054df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_name'), table_name='simulations')
    op.create_index(op.f('ix_simulations_name'), 'simulations', ['name'], unique=True)
    op.create_index(op.f('ix_simulations_case_name'), 'simulations', ['case_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_case_name'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_name'), table_name='simulations')
    op.create_index(op.f('ix_simulations_name'), 'simulations', ['name'], unique=False)
    # ### end Alembic commands ###
